### ISSUE TITLE
"(MI)"QP

### ISSUE THREAD

**Issue by svigerske** [fabiofurini/QPLIB#1]
The 2nd paragraph of Section 1.1 speaks about "(MI)QP" while before, e.g., in the abstract, QP was introduced as "the family of continuous and (mixed)-integer optimization problems".
So why there is now an extra "(MI)" added?
While I still find it unusual to use QP for what is usually a MIQCQP, I think one should then stick with the notion of QP and now silently introduce MIQPs in the middle of the introduction.

I had this question as todo in the code, but that got removed without comment by af6f3f9f7. So I try it with an issue now.

**Comment by frangio68** [comment]
> So why there is now an extra "(MI)" added?

Precisely because "QP" for a problem with integer variables is unfamiliar and strange to a significant part of the audience. We want to keep using the notation throughout the paper, but at the very beginning is nice to stress the concept. Just the once.

I find it appropriate. I can very well be declared wrong.

> Someone has better references for cplex, sbb, xpress for the section on solvers?
 ...
> I had this question as todo in the code, but that got removed without comment

Point was that we didn't have any ...

	A.

**Comment by svigerske** [comment]
I find that confusing. At the very beginning, you call it QP, then, somewhere in the middle of Section 1.1  you start to call it MIQP, and from Section 2 on it is again called QP. That just shows that the authors themself do not feel comfortable with the notation they use.

You could say something like "QP, that is, quadratic problems with continuous or integer variables" to stress again that you don't mean continuous-only problems.
